-- ============================================================
-- RiskLens — Core Tables
-- ============================================================

CREATE OR REPLACE TABLE RISKLENS.CORE.CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    NATIONALITY VARCHAR(50),
    COUNTRY_OF_RESIDENCE VARCHAR(50),
    CUSTOMER_TYPE VARCHAR(20),
    RISK_RATING VARCHAR(10),
    PEP_FLAG BOOLEAN DEFAULT FALSE,
    SANCTIONS_FLAG BOOLEAN DEFAULT FALSE,
    ONBOARDING_DATE DATE,
    KYC_LAST_REVIEWED DATE,
    OCCUPATION VARCHAR(100),
    ANNUAL_INCOME NUMBER(15,2),
    SOURCE_OF_FUNDS VARCHAR(200),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(200),
    ADDRESS VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISKLENS.CORE.ACCOUNTS (
    ACCOUNT_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    ACCOUNT_TYPE VARCHAR(30),
    ACCOUNT_STATUS VARCHAR(15),
    BRANCH_CODE VARCHAR(10),
    BRANCH_NAME VARCHAR(100),
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    OPENING_DATE DATE,
    CLOSING_DATE DATE,
    CURRENT_BALANCE NUMBER(18,2),
    AVERAGE_BALANCE_30D NUMBER(18,2),
    LAST_TRANSACTION_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISKLENS.CORE.TRANSACTIONS (
    TXN_ID VARCHAR(30) PRIMARY KEY,
    TXN_TIMESTAMP TIMESTAMP_NTZ,
    ACCOUNT_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    TXN_TYPE VARCHAR(20),
    TXN_CATEGORY VARCHAR(30),
    AMOUNT NUMBER(18,2),
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    COUNTERPARTY_ACCOUNT VARCHAR(30),
    COUNTERPARTY_NAME VARCHAR(200),
    COUNTERPARTY_BANK VARCHAR(100),
    COUNTERPARTY_COUNTRY VARCHAR(50),
    CHANNEL VARCHAR(20),
    REFERENCE_NOTE VARCHAR(500),
    IS_INTERNATIONAL BOOLEAN DEFAULT FALSE,
    ORIGINATOR_COUNTRY VARCHAR(50),
    BENEFICIARY_COUNTRY VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISKLENS.CORE.LOANS (
    LOAN_ID VARCHAR(20) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    LOAN_TYPE VARCHAR(30),
    SECTOR VARCHAR(50),
    PRINCIPAL_AMOUNT NUMBER(18,2),
    OUTSTANDING_AMOUNT NUMBER(18,2),
    INTEREST_RATE NUMBER(5,2),
    DISBURSEMENT_DATE DATE,
    MATURITY_DATE DATE,
    DPD_BUCKET VARCHAR(10),
    DAYS_PAST_DUE INT DEFAULT 0,
    COLLATERAL_TYPE VARCHAR(50),
    COLLATERAL_VALUE NUMBER(18,2),
    PROVISION_AMOUNT NUMBER(18,2),
    NPA_FLAG BOOLEAN DEFAULT FALSE,
    LAST_REPAYMENT_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISKLENS.CORE.POSITIONS (
    POSITION_ID VARCHAR(20) PRIMARY KEY,
    POSITION_DATE DATE,
    CATEGORY VARCHAR(30),
    SUB_CATEGORY VARCHAR(50),
    INSTRUMENT_TYPE VARCHAR(50),
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    AMOUNT NUMBER(18,2),
    HAIRCUT_PCT NUMBER(5,2) DEFAULT 0,
    RUNOFF_RATE_PCT NUMBER(5,2) DEFAULT 0,
    MATURITY_BUCKET VARCHAR(20),
    COUNTERPARTY_TYPE VARCHAR(30),
    STRESS_SCENARIO VARCHAR(20) DEFAULT 'BASE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISKLENS.CORE.WATCHLIST (
    WATCHLIST_ID VARCHAR(20) PRIMARY KEY,
    ENTITY_NAME VARCHAR(200),
    ENTITY_TYPE VARCHAR(20),
    LIST_SOURCE VARCHAR(50),
    COUNTRY VARCHAR(50),
    ALIASES VARCHAR(500),
    DATE_LISTED DATE,
    REASON VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RISKLENS.CORE.RISK_RULES (
    RULE_ID VARCHAR(20) PRIMARY KEY,
    RULE_NAME VARCHAR(200),
    DOMAIN VARCHAR(20),
    DESCRIPTION VARCHAR(1000),
    SEVERITY VARCHAR(10),
    THRESHOLD_VALUE NUMBER(18,2),
    THRESHOLD_UNIT VARCHAR(30),
    LOOKBACK_HOURS INT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    REGULATORY_REFERENCE VARCHAR(200),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISKLENS.CORE.CASE_NOTES (
    CASE_ID VARCHAR(36) DEFAULT UUID_STRING(),
    SIGNAL_ID VARCHAR(50),
    SIGNAL_TYPE VARCHAR(30),
    ENTITY_ID VARCHAR(20),
    ENTITY_TYPE VARCHAR(20),
    FACTS VARCHAR(5000),
    RULE_TRIGGERED VARCHAR(200),
    EVIDENCE_SUMMARY VARCHAR(5000),
    RECOMMENDED_ACTION VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'DRAFT',
    CREATED_BY VARCHAR(100),
    REVIEWED_BY VARCHAR(100),
    REVIEWED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISKLENS.AUDIT.COPILOT_AUDIT_LOG (
    LOG_ID VARCHAR(36) DEFAULT UUID_STRING(),
    SESSION_ID VARCHAR(100),
    USER_NAME VARCHAR(100),
    USER_ROLE VARCHAR(100),
    QUESTION_TEXT VARCHAR(5000),
    GENERATED_SQL VARCHAR(10000),
    RETRIEVED_CHUNKS VARIANT,
    MODEL_USED VARCHAR(50),
    RESPONSE_TEXT VARCHAR(10000),
    APPROVAL_STATUS VARCHAR(20) DEFAULT 'PENDING',
    APPROVED_BY VARCHAR(100),
    APPROVED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISKLENS.AUDIT.EVALUATION_QUESTIONS (
    QUESTION_ID INT,
    DOMAIN VARCHAR(20),
    QUESTION VARCHAR(500),
    EXPECTED_ANSWER VARCHAR(2000),
    EXPECTED_SQL_PATTERN VARCHAR(1000)
);

CREATE OR REPLACE TABLE RISKLENS.REGULATORY.REGULATORY_CHUNKS (
    CHUNK_ID VARCHAR(50),
    DOC_NAME VARCHAR(200),
    DOC_TYPE VARCHAR(50),
    SECTION VARCHAR(200),
    CHUNK_TEXT VARCHAR(8000),
    CHUNK_INDEX INT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
