-- ============================================================
-- RiskLens — Dynamic Tables (Signal Detection)
-- ============================================================

-- Structuring: cash deposits just under $10K threshold
CREATE OR REPLACE DYNAMIC TABLE RISKLENS.SIGNALS.DT_STRUCTURING_SIGNALS
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT
    'SIG-STRUCT-' || ACCOUNT_ID || '-' || DATE_TRUNC('day', TXN_TIMESTAMP)::DATE::VARCHAR AS SIGNAL_ID,
    'STRUCTURING' AS SIGNAL_TYPE, 'HIGH' AS SEVERITY,
    ACCOUNT_ID AS ENTITY_ID, 'ACCOUNT' AS ENTITY_TYPE,
    COUNT(*) AS DEPOSIT_COUNT, SUM(AMOUNT) AS TOTAL_AMOUNT,
    AVG(AMOUNT) AS AVG_AMOUNT, MIN(AMOUNT) AS MIN_AMOUNT, MAX(AMOUNT) AS MAX_AMOUNT,
    MIN(TXN_TIMESTAMP) AS FIRST_TXN, MAX(TXN_TIMESTAMP) AS LAST_TXN,
    OBJECT_CONSTRUCT('deposit_count', COUNT(*), 'total_amount', SUM(AMOUNT),
        'avg_amount', AVG(AMOUNT), 'threshold', 10000,
        'pattern', 'Multiple cash deposits just below $10,000 reporting threshold') AS EVIDENCE_JSON,
    ARRAY_CONSTRUCT('STRUCTURING', 'CASH_THRESHOLD_AVOIDANCE') AS REASON_CODES,
    'RR-001' AS RULE_ID, MAX(TXN_TIMESTAMP) AS DETECTED_AT
FROM RISKLENS.CORE.TRANSACTIONS
WHERE TXN_CATEGORY = 'CASH_DEPOSIT' AND AMOUNT BETWEEN 8000 AND 9999
  AND TXN_TIMESTAMP >= DATEADD(HOUR, -72, CURRENT_TIMESTAMP())
GROUP BY ACCOUNT_ID, DATE_TRUNC('day', TXN_TIMESTAMP) HAVING COUNT(*) >= 3;

-- Layering: rapid in-out wire transfers
CREATE OR REPLACE DYNAMIC TABLE RISKLENS.SIGNALS.DT_LAYERING_SIGNALS
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
WITH credits AS (
    SELECT ACCOUNT_ID, SUM(AMOUNT) AS TOTAL_IN, COUNT(*) AS IN_COUNT,
           MIN(TXN_TIMESTAMP) AS FIRST_IN, MAX(TXN_TIMESTAMP) AS LAST_IN
    FROM RISKLENS.CORE.TRANSACTIONS
    WHERE TXN_TYPE = 'CREDIT' AND TXN_CATEGORY = 'WIRE_TRANSFER'
      AND TXN_TIMESTAMP >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP()) GROUP BY ACCOUNT_ID
), debits AS (
    SELECT ACCOUNT_ID, SUM(AMOUNT) AS TOTAL_OUT, COUNT(*) AS OUT_COUNT,
           MIN(TXN_TIMESTAMP) AS FIRST_OUT, MAX(TXN_TIMESTAMP) AS LAST_OUT
    FROM RISKLENS.CORE.TRANSACTIONS
    WHERE TXN_TYPE = 'DEBIT' AND TXN_CATEGORY = 'WIRE_TRANSFER'
      AND TXN_TIMESTAMP >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP()) GROUP BY ACCOUNT_ID
)
SELECT 'SIG-LAYER-' || c.ACCOUNT_ID AS SIGNAL_ID, 'LAYERING' AS SIGNAL_TYPE,
    'HIGH' AS SEVERITY, c.ACCOUNT_ID AS ENTITY_ID, 'ACCOUNT' AS ENTITY_TYPE,
    c.TOTAL_IN, d.TOTAL_OUT, ROUND(d.TOTAL_OUT / NULLIF(c.TOTAL_IN, 0), 2) AS IN_OUT_RATIO,
    c.IN_COUNT, d.OUT_COUNT,
    OBJECT_CONSTRUCT('total_inflow', c.TOTAL_IN, 'total_outflow', d.TOTAL_OUT,
        'in_out_ratio', ROUND(d.TOTAL_OUT / NULLIF(c.TOTAL_IN, 0), 2),
        'pattern', 'Rapid pass-through: funds received and moved out within hours') AS EVIDENCE_JSON,
    ARRAY_CONSTRUCT('LAYERING', 'RAPID_PASS_THROUGH') AS REASON_CODES,
    'RR-002' AS RULE_ID, GREATEST(c.LAST_IN, d.LAST_OUT) AS DETECTED_AT
FROM credits c JOIN debits d ON c.ACCOUNT_ID = d.ACCOUNT_ID
WHERE d.TOTAL_OUT / NULLIF(c.TOTAL_IN, 0) > 0.8 AND c.IN_COUNT >= 3 AND d.OUT_COUNT >= 3;

-- Dormant account reactivation
CREATE OR REPLACE DYNAMIC TABLE RISKLENS.SIGNALS.DT_DORMANT_REACTIVATION
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT 'SIG-DORM-' || t.ACCOUNT_ID AS SIGNAL_ID, 'DORMANT_REACTIVATION' AS SIGNAL_TYPE,
    'MEDIUM' AS SEVERITY, t.ACCOUNT_ID AS ENTITY_ID, 'ACCOUNT' AS ENTITY_TYPE,
    a.ACCOUNT_STATUS, a.LAST_TRANSACTION_DATE AS PREVIOUS_LAST_TXN,
    DATEDIFF(MONTH, a.LAST_TRANSACTION_DATE, CURRENT_DATE()) AS MONTHS_INACTIVE,
    COUNT(*) AS RECENT_TXN_COUNT, SUM(t.AMOUNT) AS RECENT_TXN_TOTAL,
    OBJECT_CONSTRUCT('months_inactive', DATEDIFF(MONTH, a.LAST_TRANSACTION_DATE, CURRENT_DATE()),
        'recent_txn_count', COUNT(*), 'recent_txn_total', SUM(t.AMOUNT),
        'pattern', 'Dormant account suddenly active with significant transaction volume') AS EVIDENCE_JSON,
    ARRAY_CONSTRUCT('DORMANT_REACTIVATION', 'SUDDEN_ACTIVITY') AS REASON_CODES,
    'RR-003' AS RULE_ID, MAX(t.TXN_TIMESTAMP) AS DETECTED_AT
FROM RISKLENS.CORE.TRANSACTIONS t JOIN RISKLENS.CORE.ACCOUNTS a ON t.ACCOUNT_ID = a.ACCOUNT_ID
WHERE (a.ACCOUNT_STATUS = 'DORMANT' OR DATEDIFF(MONTH, a.LAST_TRANSACTION_DATE, CURRENT_DATE()) >= 12)
  AND t.TXN_TIMESTAMP >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
GROUP BY t.ACCOUNT_ID, a.ACCOUNT_STATUS, a.LAST_TRANSACTION_DATE HAVING COUNT(*) >= 3;

-- Fan-out transfers
CREATE OR REPLACE DYNAMIC TABLE RISKLENS.SIGNALS.DT_FAN_OUT_SIGNALS
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT 'SIG-FAN-' || ACCOUNT_ID || '-' || DATE_TRUNC('day', TXN_TIMESTAMP)::DATE::VARCHAR AS SIGNAL_ID,
    'FAN_OUT' AS SIGNAL_TYPE, 'HIGH' AS SEVERITY,
    ACCOUNT_ID AS ENTITY_ID, 'ACCOUNT' AS ENTITY_TYPE,
    COUNT(DISTINCT COUNTERPARTY_ACCOUNT) AS UNIQUE_RECIPIENTS, COUNT(*) AS TXN_COUNT, SUM(AMOUNT) AS TOTAL_AMOUNT,
    OBJECT_CONSTRUCT('unique_recipients', COUNT(DISTINCT COUNTERPARTY_ACCOUNT), 'txn_count', COUNT(*),
        'total_amount', SUM(AMOUNT), 'pattern', 'Single account distributing funds to many recipients rapidly') AS EVIDENCE_JSON,
    ARRAY_CONSTRUCT('FAN_OUT', 'RAPID_DISTRIBUTION') AS REASON_CODES,
    'RR-004' AS RULE_ID, MAX(TXN_TIMESTAMP) AS DETECTED_AT
FROM RISKLENS.CORE.TRANSACTIONS
WHERE TXN_TYPE = 'DEBIT' AND TXN_TIMESTAMP >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP())
GROUP BY ACCOUNT_ID, DATE_TRUNC('day', TXN_TIMESTAMP) HAVING COUNT(DISTINCT COUNTERPARTY_ACCOUNT) >= 20;

-- Watchlist hits
CREATE OR REPLACE DYNAMIC TABLE RISKLENS.SIGNALS.DT_WATCHLIST_HITS
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT 'SIG-WL-' || t.TXN_ID AS SIGNAL_ID, 'WATCHLIST_MATCH' AS SIGNAL_TYPE,
    'CRITICAL' AS SEVERITY, t.ACCOUNT_ID AS ENTITY_ID, 'ACCOUNT' AS ENTITY_TYPE,
    t.TXN_ID, t.COUNTERPARTY_NAME, w.ENTITY_NAME AS WATCHLIST_ENTITY,
    w.LIST_SOURCE, w.REASON AS WATCHLIST_REASON, t.AMOUNT, t.TXN_TIMESTAMP,
    OBJECT_CONSTRUCT('txn_id', t.TXN_ID, 'counterparty', t.COUNTERPARTY_NAME,
        'watchlist_entity', w.ENTITY_NAME, 'list_source', w.LIST_SOURCE,
        'match_reason', w.REASON, 'amount', t.AMOUNT,
        'pattern', 'Transaction counterparty matches sanctioned/watchlisted entity') AS EVIDENCE_JSON,
    ARRAY_CONSTRUCT('WATCHLIST_MATCH', w.LIST_SOURCE) AS REASON_CODES,
    'RR-005' AS RULE_ID, t.TXN_TIMESTAMP AS DETECTED_AT
FROM RISKLENS.CORE.TRANSACTIONS t JOIN RISKLENS.CORE.WATCHLIST w
    ON (t.COUNTERPARTY_NAME ILIKE '%' || w.ENTITY_NAME || '%' OR w.ALIASES ILIKE '%' || t.COUNTERPARTY_NAME || '%')
WHERE w.IS_ACTIVE = TRUE AND t.TXN_TIMESTAMP >= DATEADD(DAY, -30, CURRENT_TIMESTAMP());

-- LCR Monitor
CREATE OR REPLACE DYNAMIC TABLE RISKLENS.SIGNALS.DT_LCR_MONITOR
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
WITH daily_lcr AS (
    SELECT POSITION_DATE,
        SUM(CASE WHEN CATEGORY = 'HQLA_L1' THEN AMOUNT * (1 - HAIRCUT_PCT/100) ELSE 0 END) AS HQLA_L1,
        SUM(CASE WHEN CATEGORY = 'HQLA_L2A' THEN AMOUNT * (1 - HAIRCUT_PCT/100) ELSE 0 END) AS HQLA_L2A,
        SUM(CASE WHEN CATEGORY = 'HQLA_L2B' THEN AMOUNT * (1 - HAIRCUT_PCT/100) ELSE 0 END) AS HQLA_L2B,
        SUM(CASE WHEN CATEGORY = 'CASH_OUTFLOW' THEN AMOUNT * RUNOFF_RATE_PCT/100 ELSE 0 END) AS TOTAL_OUTFLOWS,
        SUM(CASE WHEN CATEGORY = 'CASH_INFLOW' THEN AMOUNT ELSE 0 END) AS TOTAL_INFLOWS
    FROM RISKLENS.CORE.POSITIONS WHERE STRESS_SCENARIO = 'BASE' GROUP BY POSITION_DATE
)
SELECT 'SIG-LCR-' || POSITION_DATE::VARCHAR AS SIGNAL_ID, 'LCR_MONITOR' AS SIGNAL_TYPE,
    CASE WHEN ROUND((HQLA_L1+HQLA_L2A+HQLA_L2B)/NULLIF(TOTAL_OUTFLOWS-LEAST(TOTAL_INFLOWS,TOTAL_OUTFLOWS*0.75),0)*100,2) < 100 THEN 'CRITICAL'
         WHEN ROUND((HQLA_L1+HQLA_L2A+HQLA_L2B)/NULLIF(TOTAL_OUTFLOWS-LEAST(TOTAL_INFLOWS,TOTAL_OUTFLOWS*0.75),0)*100,2) < 110 THEN 'HIGH'
         ELSE 'MEDIUM' END AS SEVERITY,
    'BANK_WIDE' AS ENTITY_ID, 'INSTITUTION' AS ENTITY_TYPE, POSITION_DATE,
    HQLA_L1, HQLA_L2A, HQLA_L2B, HQLA_L1+HQLA_L2A+HQLA_L2B AS TOTAL_HQLA,
    TOTAL_OUTFLOWS, TOTAL_INFLOWS,
    TOTAL_OUTFLOWS - LEAST(TOTAL_INFLOWS, TOTAL_OUTFLOWS * 0.75) AS NET_OUTFLOWS,
    ROUND((HQLA_L1+HQLA_L2A+HQLA_L2B)/NULLIF(TOTAL_OUTFLOWS-LEAST(TOTAL_INFLOWS,TOTAL_OUTFLOWS*0.75),0)*100,2) AS LCR_RATIO,
    OBJECT_CONSTRUCT('lcr_ratio', ROUND((HQLA_L1+HQLA_L2A+HQLA_L2B)/NULLIF(TOTAL_OUTFLOWS-LEAST(TOTAL_INFLOWS,TOTAL_OUTFLOWS*0.75),0)*100,2),
        'total_hqla', HQLA_L1+HQLA_L2A+HQLA_L2B, 'net_outflows', TOTAL_OUTFLOWS-LEAST(TOTAL_INFLOWS,TOTAL_OUTFLOWS*0.75),
        'regulatory_min', 100) AS EVIDENCE_JSON,
    'RR-007' AS RULE_ID, CURRENT_TIMESTAMP() AS DETECTED_AT
FROM daily_lcr;

-- Credit early warning
CREATE OR REPLACE DYNAMIC TABLE RISKLENS.SIGNALS.DT_CREDIT_EARLY_WARNING
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
WITH sector_metrics AS (
    SELECT SECTOR, COUNT(*) AS LOAN_COUNT, SUM(OUTSTANDING_AMOUNT) AS TOTAL_OUTSTANDING,
        SUM(CASE WHEN NPA_FLAG THEN OUTSTANDING_AMOUNT ELSE 0 END) AS NPA_AMOUNT,
        ROUND(SUM(CASE WHEN NPA_FLAG THEN OUTSTANDING_AMOUNT ELSE 0 END)/NULLIF(SUM(OUTSTANDING_AMOUNT),0)*100,2) AS NPA_RATIO,
        SUM(CASE WHEN DPD_BUCKET IN ('61-90','90+') THEN 1 ELSE 0 END) AS HIGH_DPD_COUNT,
        SUM(PROVISION_AMOUNT) AS TOTAL_PROVISIONS,
        ROUND(SUM(OUTSTANDING_AMOUNT)/NULLIF((SELECT SUM(OUTSTANDING_AMOUNT) FROM RISKLENS.CORE.LOANS),0)*100,2) AS CONCENTRATION_PCT
    FROM RISKLENS.CORE.LOANS GROUP BY SECTOR
)
SELECT 'SIG-CREDIT-' || SECTOR AS SIGNAL_ID, 'CREDIT_RISK' AS SIGNAL_TYPE,
    CASE WHEN NPA_RATIO > 5 THEN 'HIGH' WHEN CONCENTRATION_PCT > 25 THEN 'MEDIUM' ELSE 'LOW' END AS SEVERITY,
    SECTOR AS ENTITY_ID, 'SECTOR' AS ENTITY_TYPE,
    LOAN_COUNT, TOTAL_OUTSTANDING, NPA_AMOUNT, NPA_RATIO, HIGH_DPD_COUNT, TOTAL_PROVISIONS, CONCENTRATION_PCT,
    OBJECT_CONSTRUCT('sector', SECTOR, 'npa_ratio', NPA_RATIO, 'concentration_pct', CONCENTRATION_PCT,
        'high_dpd_count', HIGH_DPD_COUNT, 'total_provisions', TOTAL_PROVISIONS) AS EVIDENCE_JSON,
    CASE WHEN NPA_RATIO > 5 THEN ARRAY_CONSTRUCT('NPA_BREACH','CREDIT_DETERIORATION')
         WHEN CONCENTRATION_PCT > 25 THEN ARRAY_CONSTRUCT('CONCENTRATION_RISK')
         ELSE ARRAY_CONSTRUCT('MONITORING') END AS REASON_CODES,
    CASE WHEN NPA_RATIO > 5 THEN 'RR-008' WHEN CONCENTRATION_PCT > 25 THEN 'RR-009' ELSE NULL END AS RULE_ID,
    CURRENT_TIMESTAMP() AS DETECTED_AT
FROM sector_metrics WHERE NPA_RATIO > 3 OR CONCENTRATION_PCT > 20;

-- Consolidated alerts (union of all signals)
CREATE OR REPLACE DYNAMIC TABLE RISKLENS.SIGNALS.DT_CONSOLIDATED_ALERTS
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT SIGNAL_ID, SIGNAL_TYPE, SEVERITY, ENTITY_ID, ENTITY_TYPE, EVIDENCE_JSON, REASON_CODES, RULE_ID, DETECTED_AT FROM RISKLENS.SIGNALS.DT_STRUCTURING_SIGNALS
UNION ALL SELECT SIGNAL_ID, SIGNAL_TYPE, SEVERITY, ENTITY_ID, ENTITY_TYPE, EVIDENCE_JSON, REASON_CODES, RULE_ID, DETECTED_AT FROM RISKLENS.SIGNALS.DT_LAYERING_SIGNALS
UNION ALL SELECT SIGNAL_ID, SIGNAL_TYPE, SEVERITY, ENTITY_ID, ENTITY_TYPE, EVIDENCE_JSON, REASON_CODES, RULE_ID, DETECTED_AT FROM RISKLENS.SIGNALS.DT_DORMANT_REACTIVATION
UNION ALL SELECT SIGNAL_ID, SIGNAL_TYPE, SEVERITY, ENTITY_ID, ENTITY_TYPE, EVIDENCE_JSON, REASON_CODES, RULE_ID, DETECTED_AT FROM RISKLENS.SIGNALS.DT_FAN_OUT_SIGNALS
UNION ALL SELECT SIGNAL_ID, SIGNAL_TYPE, SEVERITY, ENTITY_ID, ENTITY_TYPE, EVIDENCE_JSON, REASON_CODES, RULE_ID, DETECTED_AT FROM RISKLENS.SIGNALS.DT_WATCHLIST_HITS
UNION ALL SELECT SIGNAL_ID, SIGNAL_TYPE, SEVERITY, ENTITY_ID, ENTITY_TYPE, EVIDENCE_JSON, REASON_CODES, RULE_ID, DETECTED_AT FROM RISKLENS.SIGNALS.DT_CREDIT_EARLY_WARNING
UNION ALL SELECT SIGNAL_ID, SIGNAL_TYPE, SEVERITY, ENTITY_ID, ENTITY_TYPE, EVIDENCE_JSON, NULL AS REASON_CODES, RULE_ID, DETECTED_AT FROM RISKLENS.SIGNALS.DT_LCR_MONITOR;
