-- ============================================================
-- RiskLens — Governance (Roles, Masking, Tags)
-- ============================================================

-- Roles
CREATE ROLE IF NOT EXISTS RISKLENS_ANALYST;
CREATE ROLE IF NOT EXISTS RISKLENS_MLRO;
CREATE ROLE IF NOT EXISTS RISKLENS_COMPLIANCE_OFFICER;
GRANT ROLE RISKLENS_ANALYST TO ROLE RISKLENS_COMPLIANCE_OFFICER;
GRANT ROLE RISKLENS_COMPLIANCE_OFFICER TO ROLE RISKLENS_MLRO;
GRANT ROLE RISKLENS_MLRO TO ROLE ACCOUNTADMIN;

-- Grants
GRANT USAGE ON DATABASE RISKLENS TO ROLE RISKLENS_ANALYST;
GRANT USAGE ON DATABASE RISKLENS TO ROLE RISKLENS_MLRO;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RISKLENS TO ROLE RISKLENS_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RISKLENS TO ROLE RISKLENS_MLRO;
GRANT SELECT ON ALL TABLES IN SCHEMA RISKLENS.CORE TO ROLE RISKLENS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RISKLENS.CORE TO ROLE RISKLENS_MLRO;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA RISKLENS.SIGNALS TO ROLE RISKLENS_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA RISKLENS.SIGNALS TO ROLE RISKLENS_MLRO;
GRANT INSERT, UPDATE ON TABLE RISKLENS.CORE.CASE_NOTES TO ROLE RISKLENS_MLRO;
GRANT INSERT ON TABLE RISKLENS.AUDIT.COPILOT_AUDIT_LOG TO ROLE RISKLENS_MLRO;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE RISKLENS_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE RISKLENS_MLRO;

-- Masking policies
CREATE OR REPLACE MASKING POLICY RISKLENS.GOVERNANCE.MASK_PII_NAME AS (val STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('RISKLENS_MLRO','ACCOUNTADMIN') THEN val ELSE CONCAT(LEFT(val,1),'***') END;
CREATE OR REPLACE MASKING POLICY RISKLENS.GOVERNANCE.MASK_EMAIL AS (val STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('RISKLENS_MLRO','ACCOUNTADMIN') THEN val ELSE CONCAT(LEFT(val,2),'***@',SPLIT_PART(val,'@',2)) END;
CREATE OR REPLACE MASKING POLICY RISKLENS.GOVERNANCE.MASK_PHONE AS (val STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('RISKLENS_MLRO','ACCOUNTADMIN') THEN val ELSE CONCAT('***-***-',RIGHT(val,4)) END;

ALTER TABLE RISKLENS.CORE.CUSTOMERS MODIFY COLUMN FIRST_NAME SET MASKING POLICY RISKLENS.GOVERNANCE.MASK_PII_NAME;
ALTER TABLE RISKLENS.CORE.CUSTOMERS MODIFY COLUMN LAST_NAME SET MASKING POLICY RISKLENS.GOVERNANCE.MASK_PII_NAME;
ALTER TABLE RISKLENS.CORE.CUSTOMERS MODIFY COLUMN EMAIL SET MASKING POLICY RISKLENS.GOVERNANCE.MASK_EMAIL;
ALTER TABLE RISKLENS.CORE.CUSTOMERS MODIFY COLUMN PHONE SET MASKING POLICY RISKLENS.GOVERNANCE.MASK_PHONE;

-- Tags
CREATE OR REPLACE TAG RISKLENS.GOVERNANCE.SENSITIVITY_LEVEL ALLOWED_VALUES 'PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED';
CREATE OR REPLACE TAG RISKLENS.GOVERNANCE.DATA_DOMAIN ALLOWED_VALUES 'AML','CREDIT_RISK','LIQUIDITY','KYC','OPERATIONS';
CREATE OR REPLACE TAG RISKLENS.GOVERNANCE.PII ALLOWED_VALUES 'TRUE','FALSE';

ALTER TABLE RISKLENS.CORE.CUSTOMERS SET TAG RISKLENS.GOVERNANCE.SENSITIVITY_LEVEL='RESTRICTED', RISKLENS.GOVERNANCE.DATA_DOMAIN='KYC';
ALTER TABLE RISKLENS.CORE.TRANSACTIONS SET TAG RISKLENS.GOVERNANCE.SENSITIVITY_LEVEL='CONFIDENTIAL', RISKLENS.GOVERNANCE.DATA_DOMAIN='AML';
ALTER TABLE RISKLENS.CORE.LOANS SET TAG RISKLENS.GOVERNANCE.SENSITIVITY_LEVEL='CONFIDENTIAL', RISKLENS.GOVERNANCE.DATA_DOMAIN='CREDIT_RISK';
ALTER TABLE RISKLENS.CORE.POSITIONS SET TAG RISKLENS.GOVERNANCE.SENSITIVITY_LEVEL='CONFIDENTIAL', RISKLENS.GOVERNANCE.DATA_DOMAIN='LIQUIDITY';
ALTER TABLE RISKLENS.CORE.CUSTOMERS MODIFY COLUMN FIRST_NAME SET TAG RISKLENS.GOVERNANCE.PII='TRUE';
ALTER TABLE RISKLENS.CORE.CUSTOMERS MODIFY COLUMN LAST_NAME SET TAG RISKLENS.GOVERNANCE.PII='TRUE';
ALTER TABLE RISKLENS.CORE.CUSTOMERS MODIFY COLUMN EMAIL SET TAG RISKLENS.GOVERNANCE.PII='TRUE';
ALTER TABLE RISKLENS.CORE.CUSTOMERS MODIFY COLUMN PHONE SET TAG RISKLENS.GOVERNANCE.PII='TRUE';

-- FK Integrity Check view
CREATE OR REPLACE VIEW RISKLENS.AUDIT.FK_INTEGRITY_CHECK AS
SELECT 'ACCOUNTS→CUSTOMERS' AS RELATIONSHIP, COUNT(*) AS ORPHAN_COUNT FROM RISKLENS.CORE.ACCOUNTS a WHERE NOT EXISTS (SELECT 1 FROM RISKLENS.CORE.CUSTOMERS c WHERE c.CUSTOMER_ID = a.CUSTOMER_ID)
UNION ALL SELECT 'TRANSACTIONS→ACCOUNTS', COUNT(*) FROM RISKLENS.CORE.TRANSACTIONS t WHERE t.ACCOUNT_ID LIKE 'ACC-%' AND NOT EXISTS (SELECT 1 FROM RISKLENS.CORE.ACCOUNTS a WHERE a.ACCOUNT_ID = t.ACCOUNT_ID)
UNION ALL SELECT 'TRANSACTIONS→CUSTOMERS', COUNT(*) FROM RISKLENS.CORE.TRANSACTIONS t WHERE t.CUSTOMER_ID LIKE 'CUST-%' AND NOT EXISTS (SELECT 1 FROM RISKLENS.CORE.CUSTOMERS c WHERE c.CUSTOMER_ID = t.CUSTOMER_ID)
UNION ALL SELECT 'LOANS→ACCOUNTS', COUNT(*) FROM RISKLENS.CORE.LOANS l WHERE NOT EXISTS (SELECT 1 FROM RISKLENS.CORE.ACCOUNTS a WHERE a.ACCOUNT_ID = l.ACCOUNT_ID)
UNION ALL SELECT 'LOANS→CUSTOMERS', COUNT(*) FROM RISKLENS.CORE.LOANS l WHERE NOT EXISTS (SELECT 1 FROM RISKLENS.CORE.CUSTOMERS c WHERE c.CUSTOMER_ID = l.CUSTOMER_ID);
